# $path = /home/denis/Pictures/walpeper/AnimeWalperper/hyperland_kath.jpg
# $path = /home/denis/Pictures/walpeper/wallpapers/wallhaven-2e2xyx.jpg
$path = /home/denis/Pictures/walpeper/wallpapers/59919008_p0.png

wallpaper {
    monitor = eDP-1
    path = $path
    fit_mode = cover
}
