windowrule = match:class ^(org.telegram.desktop)$, float on,center on, size 1280 720
windowrule = match:class ^(com/fstl-app/fstl.https://github.fstl)$, float on,center on, size 1280 720

windowrule = match:class ^(firefox)$, match:title .*Library$, float on,center on, size 1280 720
windowrule = match:class satty, float on,center on
windowrule = match:class gpicview, float on,center on, size 1280 720
windowrule = match:class clipse, float on,center on, size 620 650

# Ignore maximize requests from apps
# windowrulev2 = suppressevent maximize, class:.*
# Fix XWayland drag / focus bugs
# windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

